apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.zeppelin-name" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: zeppelin
spec:
{{- if .Values.zeppelin.nodePort }}
  type: NodePort
{{- end }}
  ports:
    - port: {{ .Values.zeppelin.servicePort }}
      targetPort: {{ .Values.zeppelin.containerPort }}
{{- if .Values.zeppelin.nodePort }}
      nodePort: {{ .Values.zeppelin.nodePort }}
{{- end }}
  selector:
    release: {{ .Release.Name | quote }}
    component: zeppelin
